/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab4;
import javax.swing.JOptionPane;
/**
 *
 * @author KALAHI CIDSS
 */
public class Lab4 extends javax.swing.JFrame {
    private Circular c;
    private Linear l;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lab4.class.getName());

    /**
     * Creates new form Lab4
     */
    public Lab4() {
        this.c = new Circular(10);
        this.l = new Linear(10);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        Input = new javax.swing.JTextField();
        Cradio = new javax.swing.JRadioButton();
        Lradio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Dequeued = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(204, 204, 204));
        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Display.setRows(5);
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(Display);

        Input.setBackground(new java.awt.Color(255, 255, 255));
        Input.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Input.setForeground(new java.awt.Color(0, 0, 0));
        Input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input.setText("Input Values");
        Input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        Cradio.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Cradio);
        Cradio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Cradio.setForeground(new java.awt.Color(255, 255, 255));
        Cradio.setSelected(true);
        Cradio.setText("Circular");
        Cradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lradio.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Lradio);
        Lradio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lradio.setForeground(new java.awt.Color(255, 255, 255));
        Lradio.setText("Linear");
        Lradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Lradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LradioActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Change Queue Type (Reset)");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Enqueue");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Dequeue");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Dequeued.setEditable(false);
        Dequeued.setBackground(new java.awt.Color(204, 204, 204));
        Dequeued.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Dequeued.setForeground(new java.awt.Color(0, 0, 0));
        Dequeued.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Dequeued.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Dequeued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DequeuedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dequeued Value:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lradio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Dequeued, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Cradio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Input, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dequeued)
                        .addGap(18, 18, 18)
                        .addComponent(Cradio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lradio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isCircular()){
            this.c = new Circular(10);
        } else if (isLinear()){
            this.l = new Linear(10);
        }
        Display.setText("");
        Dequeued.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input = Input.getText();
        try {
            Float.parseFloat(input);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Input numeric values","Input Error",JOptionPane.ERROR_MESSAGE);
            Input.setText("");
            return;
        }
        try {
            Integer.parseInt(input);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Input integer values","Input Error",JOptionPane.ERROR_MESSAGE);
            Input.setText("");
            return;
        }
        if (isCircular()){
            if (c.isFull()){
                JOptionPane.showMessageDialog(this, "Queue capacity reached", "Queue Overflow", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                c.enqueue(Integer.parseInt(input));
            }
            
        } else if (isLinear()){
            if (l.isFull()){
                JOptionPane.showMessageDialog(this, "Queue capacity reached", "Queue Overflow", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                l.enqueue(Integer.parseInt(input));
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Error");
            return;
        }
        Input.setText("");
        Display();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LradioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (isCircular()){
            if (c.isEmpty()){
                JOptionPane.showMessageDialog(this, "No value to dequeue", "Queue Underflow", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Dequeued.setText(String.valueOf(c.dequeue()));
        } else if (isLinear()){
            if (l.isEmpty()){
                JOptionPane.showMessageDialog(this, "No value to dequeue", "Queue Underflow", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Dequeued.setText(String.valueOf(l.dequeue()));
        } else {
            JOptionPane.showMessageDialog(this, "Error");
            return;
        }
        Display();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void DequeuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DequeuedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DequeuedActionPerformed

    private boolean isCircular(){
        return Cradio.isSelected();
    }
    private boolean isLinear(){
        return Lradio.isSelected();
    }
    private void Display(){
        if (isCircular()){
            Display.setText(c.display());
        } else if (isLinear()){
            Display.setText(l.display());
        } else {
            Display.setText("");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lab4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cradio;
    private javax.swing.JTextField Dequeued;
    private javax.swing.JTextArea Display;
    private javax.swing.JTextField Input;
    private javax.swing.JRadioButton Lradio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
